name: {{project_name.snakeCase()}}
description: {{{description}}}
version: 0.1.0
{{^publishable}}publish_to: none{{/publishable}}

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.32.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  lintervention: ^0.3.1
  mocktail: ^1.0.4
