name: {{project_name.snakeCase()}}
description: {{{description}}}
version: 0.1.0
{{^publishable}}publish_to: none{{/publishable}}
{{#workspace}}resolution: workspace{{/workspace}}

environment:
  sdk: ">=3.9.0 <4.0.0"
  flutter: ">=3.35.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  lintervention: ^0.4.0
  mocktail: ^1.0.4
