name: {{project_name.snakeCase()}}
description: {{{description}}}
version: 0.1.0
{{^publishable}}publish_to: none{{/publishable}}

environment:
  sdk: ">=3.0.0 <4.0.0"

dev_dependencies:
  lintervention: ^0.1.1
  mocktail: ^1.0.3
  test: ^1.25.2
