name: {{project_name.snakeCase()}}
description: {{{description}}}
version: 0.1.0+1
{{^publishable}}publish_to: none{{/publishable}}

environment:
  sdk: ">=3.0.0 <4.0.0"

dev_dependencies:
  mocktail: ^1.0.3
  test: ^1.25.2
  lintervention: ^0.1.1
  {{#main}}melos: ^5.2.1{{/main}}
