name: {{project_name.snakeCase()}}
description: {{{description}}}
version: 0.1.0
publish_to: none

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.32.0"

dev_dependencies:
  lintervention: ^0.3.1
  melos: ^6.3.3
